In [46]:
import numpy as np

arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
round(np.percentile(np.array(arr), 25))
#sorted(enumerate([[1, 2, 3, 4], [5, 6, 7, 8]]), key=lambda x: sum(x[1]), reverse=True)


3

In [37]:
num_players = 4 
num_abilities = 5

player = [4, 7, 3, 9, 2]  # Replace with your player's list
partners = np.random.randint(0, 10, size=(num_players-1, num_abilities)) 
tasks = np.random.randint(0, 10, size=(num_players*2, num_abilities))

# Create a list of all zipped player/partner combinations
partnered_abilities = np.array([player] + [[int(max(p, q)) for p, q in zip(player, partner)] for partner in partners])
print(f"partnered_abilities: {partnered_abilities, type(partnered_abilities)}")

# Get penalty Matrix 
partnered_abilities = np.array(partnered_abilities) 
penalty_matrix = [] 

for i, team in enumerate(partnered_abilities):
    print(i, team)
    penalties = []
    for task_index, task in enumerate(tasks):
        # Calculate energy expended as the sum of positive differences split between two partners
        print(task, team)
        penalty = np.sum(np.maximum(0, task - team)) / 2
        print(f"penalty: {penalty}")
        # First value is individual completing the task
        if i == 0:
            penalty = penalty * 2
        penalties.append((task_index, penalty))
    penalty_matrix.append(penalties)

    
    
# bids: [task_index, partner.id]
print(penalty_matrix)


partnered_abilities: (array([[4, 7, 3, 9, 2],
       [7, 7, 5, 9, 2],
       [4, 7, 3, 9, 2],
       [8, 7, 3, 9, 9]]), <class 'numpy.ndarray'>)
0 [4 7 3 9 2]
[2 3 1 3 3] [4 7 3 9 2]
penalty: 0.5
[3 9 0 1 5] [4 7 3 9 2]
penalty: 2.5
[0 9 3 7 7] [4 7 3 9 2]
penalty: 3.5
[8 1 6 0 6] [4 7 3 9 2]
penalty: 5.5
[6 1 2 7 5] [4 7 3 9 2]
penalty: 2.5
[0 2 7 7 6] [4 7 3 9 2]
penalty: 4.0
[8 7 6 3 8] [4 7 3 9 2]
penalty: 6.5
[0 0 8 7 2] [4 7 3 9 2]
penalty: 2.5
1 [7 7 5 9 2]
[2 3 1 3 3] [7 7 5 9 2]
penalty: 0.5
[3 9 0 1 5] [7 7 5 9 2]
penalty: 2.5
[0 9 3 7 7] [7 7 5 9 2]
penalty: 3.5
[8 1 6 0 6] [7 7 5 9 2]
penalty: 3.0
[6 1 2 7 5] [7 7 5 9 2]
penalty: 1.5
[0 2 7 7 6] [7 7 5 9 2]
penalty: 3.0
[8 7 6 3 8] [7 7 5 9 2]
penalty: 4.0
[0 0 8 7 2] [7 7 5 9 2]
penalty: 1.5
2 [4 7 3 9 2]
[2 3 1 3 3] [4 7 3 9 2]
penalty: 0.5
[3 9 0 1 5] [4 7 3 9 2]
penalty: 2.5
[0 9 3 7 7] [4 7 3 9 2]
penalty: 3.5
[8 1 6 0 6] [4 7 3 9 2]
penalty: 5.5
[6 1 2 7 5] [4 7 3 9 2]
penalty: 2.5
[0 2 7 7 6] [4 7 3 9 2]
penalty: 4.0

In [13]:
player = enumerate(partners)
player

In [14]:
for i, p in enumerate(player):
    print(i, p)

0 (0, [5, 6, 8, 3, 4])
1 (1, [1, 9, 2, 5, 8])
2 (2, [6, 4, 7, 8, 1])
3 (3, [3, 5, 6, 4, 7])


In [4]:
import numpy as np
import pandas as pd

def calculate_penalty_matrix(players, tasks):
    """
    Calculate the penalty matrix for given players and tasks.
    
    Args:
    - players: A 2D list or array where each row represents a player's abilities.
    - tasks: A 2D list or array where each row represents a task's requirements.
    
    Returns:
    - A 2D numpy array containing the penalties for each player-task pair.
    """
    players = np.array(players)
    tasks = np.array(tasks)
    penalty_matrix = []
    
    for player in players:
        penalties = []
        for task in tasks:
            # Calculate energy expended as the sum of positive differences
            penalty = np.sum(np.maximum(0, task - player))
            penalties.append(penalty)
        penalty_matrix.append(penalties)
    
    return np.array(penalty_matrix)

# Example data
players = [
    [2, 8, 4, 7],
    [5, 6, 3, 2]
]

tasks = [
    [1, 10, 3, 7],
    [4, 7, 2, 6]
]

# Calculate the penalty matrix
penalty_matrix = calculate_penalty_matrix(players, tasks)

# Convert to DataFrame for better readability (optional)
penalty_df = pd.DataFrame(
    penalty_matrix, 
    index=[f'Player {i+1}' for i in range(len(players))],
    columns=[f'Task {j+1}' for j in range(len(tasks))]
)

print(penalty_df)


          Task 1  Task 2
Player 1       2       2
Player 2       9       5


In [3]:
import numpy as np
from scipy.optimize import linear_sum_assignment

def minimize_sum(matrix):
    """
    Find the minimum sum by assigning each column a unique value from a row
    such that no two values come from the same row or column.
    
    Args:
    - matrix: A 2D numpy array (p x t) where p represents rows and t represents columns.
    
    Returns:
    - total_sum: The minimum sum achieved.
    - assignment: List of (row, column) assignments for the minimum sum.
    """
    # Use the Hungarian algorithm
    row_indices, col_indices = linear_sum_assignment(matrix)
    
    # Calculate the minimum sum
    total_sum = matrix[row_indices, col_indices].sum()
    
    # Return the sum and the assignments
    return total_sum, list(zip(row_indices, col_indices))

# Example matrix (p x t)
matrix = np.array([
    [4, 1, 3],
    [2, 0, 5],
    [3, 2, 2]
])

# Find the minimum sum and assignment
min_sum, assignments = minimize_sum(matrix)

# Output the results
print("Minimum Sum:", min_sum)
print("Assignments (row -> column):", assignments)


Minimum Sum: 5
Assignments (row -> column): [(np.int64(0), np.int64(1)), (np.int64(1), np.int64(0)), (np.int64(2), np.int64(2))]
